Detected,Issue,Related to Tensor,Version,Buggy API,Category,Impact,Log Rule,Log Message,Category.1,Trigger Mechanism,Description,Need More Inspection(0/1),Reason not agree,Unnamed: 14,Time,Related,CUDA
ACETest,https://github.com/tensorflow/tensorflow/issues/62146,yes,2.14.0,tf.raw_ops.BiasAdd,Vulnerability,Check failed,Aborted (core dumped),"2023-10-18 13:29:08.644285: F tensorflow/core/framework/tensor_shape.cc:357] Check failed: d < dims() (2 vs. 2)
Aborted (core dumped)",API Input Context,Generating Tensors with Incompatible Shapes,Improper input validation,,,,2023-10-18T05:32:47Z,1.0,cu118
,https://github.com/tensorflow/tensorflow/issues/62142,yes,2.14.0,tf.raw_ops.Conv2DBackpropFilter,Vulnerability,Check failed,Aborted (core dumped),"2023-10-18 01:54:46.384973: F ./tensorflow/core/util/tensor_format.h:428] Check failed: index >= 0 && index < num_total_dims Invalid index from the dimension: 3, 0,
Aborted (core dumped)",API Input Context,Generating Tensors with Incompatible Shapes,Improper input validation,,,,2023-10-17T17:58:27Z,1.0,cu118
ACETest,https://github.com/tensorflow/tensorflow/issues/62140,yes,2.14.0,tf.raw_ops.BiasAddGrad,Vulnerability,Check failed,Aborted (core dumped),"2023-10-17 22:20:56.471424: F tensorflow/core/framework/tensor_shape.cc:357] Check failed: d < dims() (2 vs. 2)
Aborted (core dumped)",API Input Context,Generating Tensors with Incompatible Shapes,Improper input validation,,,,2023-10-17T14:32:50Z,1.0,N.A
ACETest,https://github.com/tensorflow/tensorflow/issues/62055,yes,2.14.0,tf.raw_ops.QuantizeAndDequantizeV4,Vulnerability,Check failed,Aborted (core dumped),"2023-10-05 23:52:38.268849: F tensorflow/core/framework/tensor.cc:852] Check failed: 1 == NumElements() (1 vs. 0)Must have a one element tensor
Aborted (core dumped)",API Input Context,Empty Input Tensor,core dumped error with specific input parameters,,,,2023-10-05T15:56:08Z,1.0,cu118
,https://github.com/tensorflow/tensorflow/issues/61761,yes,2.14.0,tf.raw_ops.Enter,Logical,NotFoundError,Could not find device for node,"tensorflow.python.framework.errors_impl.NotFoundError: Could not find device for node: {{node Enter}} = Enter[T=DT_QINT8, frame_name=""test"", is_constant=true, parallel_iterations=10]
All kernels registered for op Enter:",API Input Context,Supporting Specific Data Types,,,,,2023-08-31T08:49:00Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/60764,yes,2.12.0,tf.raw_ops.Acos,Logical,AssertionError,Not equal to tolerance,"    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.0001, atol=0.0001",Test Case Context,Modeling Decorators for DL Execution Mode,,1.0,trigger is jti_compile mode with complex number,,2023-06-02T10:50:29Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/60759,yes,2.13.0,tf.raw_ops.Empty,Vulnerability,Check failed,Check failed,"2023-06-02 11:44:08.858309: F tensorflow/compiler/xla/shape_util.cc:288] Check failed: FillNewShape(element_type, dimensions, &shape) 
zsh: abort (core dumped)  python test.py",Test Case Context,Modeling Decorators for DL Execution Mode,,,,,2023-06-02T03:48:27Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/60758,yes,2.13.0,tf.raw_ops.EmptyTensorList,Vulnerability,Check failed,Check failed,"2023-06-02 11:41:06.810728: F tensorflow/core/framework/tensor_shape.cc:201] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 246417692688323817 with 562326056, result: -1
zsh: abort (core dumped)  python test.py",API Input Context,Large Input Tensor,,,,,2023-06-02T03:41:51Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/60757,yes,2.13.0,tf.raw_ops.Fill,Vulnerability,Check failed,Check failed,"2023-06-02 11:41:06.810728: F tensorflow/core/framework/tensor_shape.cc:201] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 246417692688323817 with 562326056, result: -1
zsh: abort (core dumped)  python test.py",API Input Context,Large Input Tensor,,,,,2023-06-02T03:22:05Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/60756,yes,2.13.0,tf.raw_ops.GatherV2,Vulnerability,Check failed,Check failed,"2023-06-02 11:41:06.810728: F tensorflow/core/framework/tensor_shape.cc:201] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 246417692688323817 with 562326056, result: -1
zsh: abort (core dumped)  python test.py",API Input Context,Large Input Tensor,,,,,2023-06-02T03:14:31Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/60277,yes,2.12.0,tf.raw_ops.TridiagonalMatMul,Vulnerability,integer overflow,Aborted (core dumped),"2023-04-09 14:03:32.257496: F tensorflow/core/framework/tensor_shape.cc:201] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 6291163412844499803 with 7, result: -1
Aborted (core dumped)",API Input Context,Large Input Tensor,,1.0,integer overflow should be changed to checkfail,,2023-04-09T06:05:40Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/60276,yes,2.13.0,tf.raw_ops.Gather,Vulnerability,integer overflow,Aborted (core dumped),"2023-04-09 14:03:32.257496: F tensorflow/core/framework/tensor_shape.cc:201] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 6291163412844499803 with 7, result: -1
Aborted (core dumped)",API Input Context,Large Input Tensor,,,,,2023-04-09T06:01:12Z,1.0,cu118
ACETest,https://github.com/tensorflow/tensorflow/issues/60275,yes,2.12.0,tf.raw_ops.MatrixLogarithm,Vulnerability,integer overflow,Aborted (core dumped),"2023-04-09 14:03:32.257496: F tensorflow/core/framework/tensor_shape.cc:201] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 6291163412844499803 with 7, result: -1
Aborted (core dumped)",API Input Context,Large Input Tensor,,1.0,integer overflow should be changed to checkfail,,2023-04-09T05:57:00Z,1.0,cu118
ACETest,https://github.com/tensorflow/tensorflow/issues/60273,yes,2.12.0,tf.raw_ops.UnicodeDecodeWithOffsets,Vulnerability,Check failed,Aborted (core dumped),"2023-04-09 13:47:12.779782: F tensorflow/core/framework/tensor.cc:770] Check failed: dtype() == expected_dtype (9 vs. 3) int32 expected, got int64
Aborted (core dumped)",API Input Context,Supporting Specific Data Types,,,,,2023-04-09T05:50:27Z,1.0,cu118
,https://github.com/tensorflow/tensorflow/issues/60201,yes,2.12.0,tf.raw_ops.DepthwiseConv2dNativeBackpropInput,Vulnerability,InvalidArgumentError,Aborted (core dumped),"2023-04-01 16:37:55.854746: F tensorflow/core/kernels/mkl/mkl_conv_grad_input_ops.cc:537] Non-OK-status: tensor::MakeShape(input_tensor, &input_tf_shape) status: INVALID_ARGUMENT: Dimension -510 must be >= 0
Aborted (core dumped)",API Input Context,Generating Tensors with Incompatible Shapes,,,,,2023-04-01T08:40:42Z,1.0,cu118
,https://github.com/tensorflow/tensorflow/issues/60200,yes,2.12.0,tf.raw_ops.ThreadUnsafeUnigramCandidateSampler,Vulnerability,InvalidArgumentError,Aborted (core dumped),"2023-04-01 16:37:55.854746: F tensorflow/core/kernels/mkl/mkl_conv_grad_input_ops.cc:537] Non-OK-status: tensor::MakeShape(input_tensor, &input_tf_shape) status: INVALID_ARGUMENT: Dimension -510 must be >= 0
Aborted (core dumped)",API Input Context,Large Integer Argument,,,,,2023-04-01T08:36:16Z,1.0,cu118
,https://github.com/tensorflow/tensorflow/issues/60199,yes,2.12.0,tf.raw_ops.MatrixDeterminant,Vulnerability,integer overflow,Aborted (core dumped),"2023-04-01 16:27:45.620825: F tensorflow/core/framework/tensor_shape.cc:201] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 7678600331551628182 with 15, result: -1
Aborted (core dumped)",API Input Context,Large Input Tensor,,1.0,integer overflow should be changed to checkfail,,2023-04-01T08:30:49Z,1.0,cu118
,https://github.com/tensorflow/tensorflow/issues/60197,yes,2.12.0,tf.raw_ops.LearnedUnigramCandidateSampler,Vulnerability,Check failed,Aborted (core dumped),"2023-04-01 16:20:39.689581: F tensorflow/core/kernels/range_sampler.cc:183] Check failed: range < kint32max (3031324185113192368 vs. 2147483647)
Aborted (core dumped)",API Input Context,Large Integer Argument,,,,,2023-04-01T08:23:48Z,1.0,cu118
,https://github.com/tensorflow/tensorflow/issues/60196,yes,2.12.0,tf.raw_ops.StatelessRandomGammaV2,Vulnerability,Check failed,Aborted (core dumped),"2023-04-01 16:17:28.418600: F ./tensorflow/core/util/gpu_launch_config.h:129] Check failed: work_element_count >= 0 (0 vs. -457139056)
Aborted (core dumped)",API Input Context,Empty Input Tensor,,,,,2023-04-01T08:21:17Z,1.0,cu118
,https://github.com/tensorflow/tensorflow/issues/60195,yes,2.12.0,tf.raw_ops.Conv3DBackpropFilterV2,Vulnerability,Check failed,Aborted (core dumped),"2023-04-01 15:05:15.267117: F ./tensorflow/core/util/tensor_format.h:427] Check failed: index >= 0 && index < num_total_dims Invalid index from the dimension: 1, 1, C
Aborted (core dumped)",API Input Context,Generating Tensors with Incompatible Shapes,,,,,2023-04-01T07:09:21Z,1.0,cu115
,https://github.com/tensorflow/tensorflow/issues/60059,yes,2.11.0,tf.raw_ops.QuantizeAndDequantizeV4,Logical,TypeError,takes 2 positional arguments but 4 were given,TypeError: _QuantizeAndDequantizeV4GradGrad() takes 2 positional arguments but 4 were given,Test Case Context,Modeling Multiple API Usage Pattern,,1.0,"2 arguments were passed, but expected 4, arguments are not matching",,2023-03-22T00:32:52Z,1.0,N.A
ACETest,https://github.com/tensorflow/tensorflow/issues/60034,yes,2.11.0,tf.raw_ops.CholeskyGrad,Vulnerability,integer overflow,Aborted (core dumped),"2023-03-18 18:20:26.563113: F tensorflow/core/framework/tensor_shape.cc:201] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 1152921504606846976 with 8, result: -9223372036854775808
Aborted (core dumped)",API Input Context,Large Input Tensor,,,,,2023-03-18T10:22:30Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/59960,yes,2.11.0,tf.raw_ops.CholeskyGrad,Vulnerability,TypeError,takes 2 positional arguments but 4 were given,TypeError: _QuantizeAndDequantizeV4GradGrad() takes 2 positional arguments but 4 were given,Test Case Context,Modeling Multiple API Usage Pattern,,1.0,"2 arguments were passed, but expected 4, arguments are not matching",,2023-03-12T01:12:14Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/62280,yes,2.14.0,tf.raw_ops.Acos,Logical,InvalidArgumentError,InvalidArgumentError,"    raise errors.InvalidArgumentError(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b''",API Input Context,Modeling Specific Inputs,,,,,2023-10-30T12:59:35Z,,
,https://github.com/tensorflow/tensorflow/issues/62263,yes,2.14.0,tf.raw_ops.SqrtGrad,Logical,InvalidArgumentError,InvalidArgumentError,"    raise errors.InvalidArgumentError(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b''",Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-10-28T02:08:02Z,,
,https://github.com/tensorflow/tensorflow/issues/62220,yes,2.14.0,tf.raw_ops.Asinh,Logical,InvalidArgumentError,InvalidArgumentError,"    raise errors.InvalidArgumentError(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b''",API Input Context,Modeling Specific Inputs,,,,,2023-10-25T07:04:01Z,,
,https://github.com/tensorflow/tensorflow/issues/59099,yes,2.11.0,tf.raw_ops.TensorListScatterV2,Logical,TypeError,EagerTensor of dtype variant,TypeError: Cannot convert 1 to EagerTensor of dtype variant,API Input Context,Modeling Specific Inputs,,,,,2023-01-04T20:44:47Z,,
