Detected,Issue,Related to Tensor,Version,Buggy API,Category,Impact,Log Rule,Log Message,Category.1,Trigger Mechanism,Description,Need More Inspection(0/1),Reason not agree,Unnamed: 14,Time,Related,CUDA
,https://github.com/tensorflow/tensorflow/issues/62174,yes,2.14.0,tf.map_fn,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs,tf.map_fn and TensorArray do not seem to support backpropagation,,,,2023-10-19T12:34:32Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/62114,yes,2.14.0,tf.truncatediv,Logical,Others,Internal error,Internal error,API Input Context,Zero Integer Argument,Internal Error for truncatediv when denominator is an integer zero,,,,2023-10-15T05:48:56Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/62088,yes,2.14.0,tf.gather,Logical,InvalidArgumentError,is not compatible with result shape,"tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__GatherV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Shape used to set computation result layout (s32[3,2]{1,0}) is not compatible with result shape (s32[2,2])
         [[{{node cluster_1_1/xla_compile}}]] [Op:GatherV2] name:",API Input Context,Generating Tensors with Incompatible Shapes,"But looks like the doc does not tell us what to do when the batch_dim dimensions of params and indices disagree. Should the formula be updated to something like: def batched_result_shape(p_shape, i_shape, axis=0, batch_dims=0):
return i_shape[:batch_dims] + p_shape[batch_dims:axis] + i_shape[batch_dims:] + p_shape[axis+1:] or, should we just add a validation check to count the mismatch of batch_dim dimensions of params and indices?",,,,2023-10-11T12:07:56Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/62070,yes,2.14.0,tf.truncatemod,Logical,NotFoundError,Could not find device for node,NotFoundError: Could not find device for node: {{node TruncateMod}} = TruncateMod[T=DT_BFLOAT16],API Input Context,Supporting Specific Data Types,supports the half and bfloat16 data type but in practical it does not.,,,,2023-10-09T08:36:40Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/61968,yes,2.14.0,tf.transpose,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-09-25T00:12:15Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/61965,yes,2.14.0,tf.math.floordiv,Vulnerability,InvalidArgumentError,Integer division by zero,InvalidArgumentError: Exception encountered when calling layer 'model_21' (type Model). {{function_node __wrapped__FloorDiv_device_/job:localhost/replica:0/task:0/device:CPU:0}} Integer division by zero [Op:FloorDiv] name:,API Input Context,Empty Input Tensor,,,,,2023-09-23T19:51:17Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/61955,yes,2.13.0,tf.linalg.svd,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs,,,,,2023-09-23T08:44:22Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/61925,yes,2.13.0,tf.keras.layers.Concatenate,Logical,ValueError,layer requires inputs with matching shapes,raise ValueError(err_msg) ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concatenation axis. Received:,API Input Context,Generating Tensors with Incompatible Shapes,,,,,2023-09-20T07:51:32Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/61916,yes,2.13.0,tf.linalg.cholesky,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Supporting Specific Data Types,,,,,2023-09-19T13:54:42Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/61911,no,2.13.0,tf.device,Logical,Others,cudaError_t.cudaSuccess,"(<cudaError_t.cudaSuccess: 0>, 0)
(<cudaError_t.cudaSuccess: 0>, 7)
(<cudaError_t.cudaSuccess: 0>, 7)
(<cudaError_t.cudaSuccess: 0>, 0)",API Input Context,Modeling Specific Devices,,1.0,"trigger: This happens when: 1. tensorflow is initializing GPU context on this line (tf.device), 2. there is no materialization of tensors on GPU",,2023-09-19T10:21:44Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/61907,yes,2.13.0,tf.linalg.cholesky,Logical,NotFoundError,Could not find device for node,"NotFoundError: Could not find device for node: {{node Cholesky}} = Cholesky[T=DT_HALF]
All kernels registered for op Cholesky:",API Input Context,Supporting Specific Data Types,"unsupported data type
expected to accept tensor in half precision but it fails",,,,2023-09-19T05:37:10Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/61875,yes,2.12.0,tf.cast,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Large Input Tensor,casting round issue,,,,2023-09-15T12:50:23Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/61861,yes,2.13.0,tf.nn.elu,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Others,Others,,,,,2023-09-14T13:33:11Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/61856,yes,2.13.0,tf.reshape,Logical,ValueError,Shape must be rank 1 but is rank,"ValueError: Shape must be rank 1 but is rank 0 for '{{node Reshape_1}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32](Reshape, Reshape_1/shape)' with input shapes: [2,2], [].",API Input Context,Generating Tensors with Incompatible Shapes,,,,,2023-09-13T21:09:29Z,1.0,N.A
FreeFuzz,https://github.com/tensorflow/tensorflow/issues/61780,yes,2.14.0,tf.gather,Vulnerability,Check failed,Aborted (core dumped),"v2.14.0-rc0-34-gdd01672d9a9 2.14.0-rc1
2023-09-03 13:08:24.487989: F ./tensorflow/core/util/gpu_launch_config.h:160] Check failed: work_element_count >= 0 (0 vs. -549025096)
Aborted (core dumped)",API Input Context,Large Input Tensor,,,,,2023-09-03T14:31:11Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/61712,yes,2.13.0,tf.function,Logical,ValueError,Structure of Python function inputs does not match input_signature,ValueError: Structure of Python function inputs does not match input_signature:,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-08-27T12:47:18Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/61701,yes,2.13.0,tf.math.top_k,Logical,InvalidArgumentError,was expected to be a int64 tensor,tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int64 tensor but is a int32 tensor [Op:AddV2] name:,API Input Context,Supporting Specific Data Types,,1.0,Maybe Specific Input argument?,,2023-08-25T18:38:43Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/61675,yes,2.13.0,tf.linalg.pinv,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Usage Context,Modeling Specific Inputs,,1.0,I think it's something diffrerent,,2023-08-23T13:32:23Z,1.0,N.A
DocTer,https://github.com/tensorflow/tensorflow/issues/61605,yes,2.13.0,tf.keras.layers.MaxPool2D,Vulnerability,Check failed,Allocation of,"{""pid"":7,""type"":""jupyter"",""level"":40,""msg"":""2023-08-17 14:26:40.077428: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 6093750902 exceeds 10% of free system memory."",""time"":""2023-08-17T14:26:40.077Z"",""v"":0}
{""pid"":7,""type"":""jupyter"",""level"":40,""msg"":""2023-08-17 14:26:42.860963: F tensorflow/core/framework/tensor_shape.cc:587] Check failed: size >= 0 (0 vs. -1248091845)"",""time"":""2023-08-17T14:26:42.861Z"",""v"":0}",API Input Context,Large List Element,,,,,2023-08-17T15:21:19Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/62778,yes,2.13.0,tf.shape,Logical,InvalidArgumentError,dimension 0 out of bounds,tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:GPU:0}} slice index 1 of dimension 0 out of bounds. [Op:StridedSlice] name: strided_slice/ [[{{node numpy_function_1}}]] [Op:IteratorGetNext] name:,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2024-01-11T02:23:23Z,,
,https://github.com/tensorflow/tensorflow/issues/62509,yes,2.14.0,tf.math.reduce_prod,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-11-30T09:59:49Z,,
,https://github.com/tensorflow/tensorflow/issues/62504,yes,2.14.0,tf.squeeze,Vulnerability,Others,MemoryError: std::bad_alloc,"/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/gen_array_ops.py in squeeze(input, axis, name)
  10614   if tld.is_eager:
  10615     try:
> 10616       _result = pywrap_tfe.TFE_Py_FastPathExecute(
  10617         _ctx, ""Squeeze"", name, input, ""squeeze_dims"", axis)
  10618       return _result

MemoryError: std::bad_alloc",API Input Context,Supporting Specific Data Types,,,,,2023-11-29T19:27:17Z,,
,https://github.com/tensorflow/tensorflow/issues/62441,yes,2.14.0,tf.nn.convolution,Performance bug,Performance bug,Memory Leak,Memory Leak,Test Case Context,Oracle for Performance Bug Detection,,,,,2023-11-20T15:51:19Z,,
,https://github.com/tensorflow/tensorflow/issues/62399,no,2.12.0,tf.math.log,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs,,,,,2023-11-14T23:45:40Z,,
,https://github.com/tensorflow/tensorflow/issues/61482,yes,2.13.0,tf.nn.max_pool2d,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs,,,,,2023-08-04T22:24:18Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/61421,no,2.12.0,tf.debugging.experimental.enable_dump_debug_info,Logical,ValueError,Cannot assign a device for operation,"    output_tensor_device_ids = [writer.RegisterDeviceAndGetId(output.device)
ValueError: Cannot assign a device for operation IteratorGetNextAsOptional: Could not satisfy explicit device specification '' because the node {{colocation_node IteratorGetNextAsOptional}} was colocated with a group of nodes that required incompatible device '/job:worker/replica:0/task:0/device:TPU:0'. All available devices [/job:worker/replica:0/task:0/device:CPU:0, /job:worker/replica:0/task:0/device:TPU:0, /job:worker/replica:0/task:0/device:TPU:1, /job:worker/replica:0/task:0/device:TPU:2, /job:worker/replica:0/task:0/device:TPU:3, /job:worker/replica:0/task:0/device:TPU:4, /job:worker/replica:0/task:0/device:TPU:5, /job:worker/replica:0/task:0/device:TPU:6, /job:worker/replica:0/task:0/device:TPU:7, /job:worker/replica:0/task:0/device:TPU_SYSTEM:0, /job:worker/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:COMPOSITE:0]. ",Test Case Context,Modeling Multiple API Usage Pattern,,1.0,trigger: multiple api usage,,2023-07-28T06:27:06Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/61364,no,2.12.0,tf.io.gfile.rename,Logical,FailedPreconditionError,Source is a directory or empty file,tensorflow.python.framework.errors_impl.FailedPreconditionError: Source is a directory or empty file,API Input Context,Modeling Specific Inputs,,,,,2023-07-24T14:39:54Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/61249,yes,2.13.0,tf.linalg.logdet,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Supporting Specific Data Types,,,,,2023-07-12T05:06:25Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/61162,yes,2.12.0,tf.io.read_file,Logical,ValueError,Shape must be rank 0 but is rank 1 for,   ValueError: Shape must be rank 0 but is rank 1 for '{{node ReadFile}} = ReadFile[](args_0)' with input shapes: [?].,API Input Context,Modeling Specific Inputs,,1.0,vectorizing the mapping function in the input triggers the bug,,2023-07-03T13:08:00Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/61117,yes,2.13.0,tf.math.reduce_prod,Logical,AssertionError,AssertionError,AssertionError: d2z_dydx = 0.0,API Input Context,Modeling Specific Inputs,,1.0,trigger: 0  elements in the input,,2023-06-28T16:17:39Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/60925,yes,2.14.0,tf.concat,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-06-19T18:02:40Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/60892,yes,2.13.0,tf.math.softplus,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Large Input Tensor,,1.0,trigger: large inputs after converting to lite model,,2023-06-16T05:05:57Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/60714,yes,2.12.0,tf.split,Logical,ValueError,Check failed,"ValueError: Exception encountered when calling layer ""bn3"" (type BatchNormalization).
Shape must be rank 4 but is rank 5 for '{{node bn3/FusedBatchNormV3}} = FusedBatchNormV3[T=DT_FLOAT, U=DT_FLOAT, data_format=""NHWC"", epsilon=0.001, exponential_avg_factor=1, is_training=false](Placeholder, bn3/ReadVariableOp, bn3/ReadVariableOp_1, bn3/FusedBatchNormV3/ReadVariableOp, bn3/FusedBatchNormV3/ReadVariableOp_1)' with input shapes: [1,?,128,128,32], [32], [32], [32], [32].",API Input Context,Generating Tensors with Incompatible Shapes,,,,,2023-05-26T17:33:07Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/60710,yes,2.12.0,tf.py_function,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-05-25T18:52:03Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/60549,no,2.12.0,tf.signal.inverse_stft,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,1.0,should be incorrect code pattern,,2023-05-09T20:14:39Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/60547,yes,2.14.0,tf.linalg.matrix_rank,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Usage Context,Modeling Decorators for DL Execution Mode,,,,,2023-05-09T19:42:32Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/60521,no,2.12.0,tf.nn.leaky_relu,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Usage Context,Supporting Specific Data Types,,,,,2023-05-06T09:03:07Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/60472,yes,2.12.0,tf.where,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs," I suspect this because changing the input shape to (4, ) changes the output shape to (4, )",1.0,"it's inconsistent result, trigger is two differnt input argument",,2023-05-02T16:34:56Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/60312,no,2.12.0,tf.nn.conv2d,Performance bug,Performance bug,Slow Execution,Slow Execution,Test Case Context,Oracle for Performance Bug Detection,,,,,2023-04-13T10:01:27Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/60041,yes,2.11.0,tf.math.zeta,Vulnerability,Inconsistent results,Inconsistent results,Inconsistent results,Others,Others,,,,,2023-03-20T05:15:05Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/59754,yes,2.11.0,tf.gather_nd,Logical,Others,Op: ResourceGatherNd,"Colocation members, user-requested devices, and framework assigned devices, if any:
  resource (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  ResourceGatherNd (ResourceGatherNd) /job:localhost/replica:0/task:0/device:GPU:0

Op: ResourceGatherNd
Node attrs: dtype=DT_COMPLEX64, Tindices=DT_INT64
Registered kernels:",API Input Context,Supporting Specific Data Types,,,,,2023-02-21T09:50:12Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/61646,yes,2.13.0,tf.config.experimental_connect_to_host,Vulnerability,AssertionError,Aborted,"E0819 19:02:10.839114974  187448 completion_queue.cc:244]    assertion failed: queue.num_items() == 0
Aborted",API Input Context,Modeling Specific Inputs,,,,,2023-01-22T16:31:20Z,1.0,cu118
FuzzGPT,https://github.com/tensorflow/tensorflow/issues/61600,yes,2.13.0,tf.linalg.diag,Vulnerability,integer overflow,Encountered overflow,"Error:{{function_node __wrapped__MatrixDiagV3_device_/job:localhost/replica:0/task:0/device:GPU:0}} Encountered overflow when multiplying 12884901888 with 1610612736, result: -1
         [[{{node MatrixDiagV3}}]] [Op:MatrixDiagV3]",API Input Context,Large Integer Argument,,,,,2023-01-21T19:10:02Z,1.0,cu118
,https://github.com/tensorflow/tensorflow/issues/52064,yes,2.11.0,tf.keras.layers.Conv1D,Logical,RuntimeError,failed to prepare,RuntimeError: tensorflow/lite/kernels/reshape.cc:69 num_input_elements != num_output_elements (25000 != 0)Node number 2 (RESHAPE) failed to prepare.,API Input Context,Modeling Specific Inputs,,,,,2023-01-06T14:16:14Z,1.0,N.A
,https://github.com/tensorflow/tensorflow/issues/58790,yes,2.11.0,tf.math.cumsum,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs,"My guess is that when doing cumsum on a ragged dimension, the summation is actually somehow carried out on the entirety of flat values, and then some subtractions based on row_splits turn the long cumsum list to the result at each dimension.",,,,2022-12-05T23:37:00Z,1.0,cu117
,https://github.com/tensorflow/tensorflow/issues/62205,yes,2.13.0,tf.image.resize,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs,,,,,2023-10-24T08:24:07Z,,
,https://github.com/tensorflow/tensorflow/issues/62167,yes,2.14.0,tf.pad,Vulnerability,Segmentation Fault,segmentation fault,[1]    13162 segmentation fault (core dumped)  ./benchmark_model --graph=../poc/split_v.tflite,Others,Others,,,,,2023-10-19T06:20:18Z,,
,https://github.com/tensorflow/tensorflow/issues/62089,yes,2.13.0,tf.nn.depthwise_conv2d,Vulnerability,Others,_NotOkStatusException,"     55   except core._NotOkStatusException as e:

UnknownError: Graph execution error:",Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-10-11T12:42:52Z,,
,https://github.com/tensorflow/tensorflow/issues/61907,yes,2.13.0,tf.linalg.cholesky,Logical,NotFoundError,Could not find device for node,"NotFoundError: Could not find device for node: {{node Cholesky}} = Cholesky[T=DT_HALF]
All kernels registered for op Cholesky:",API Input Context,Supporting Specific Data Types,,,,,2023-09-19T05:37:10Z,,
,https://github.com/tensorflow/tensorflow/issues/60772,yes,2.12.0,tf.math.count_nonzero,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Large Input Tensor,,,,,2023-06-03T18:23:30Z,,
,https://github.com/tensorflow/tensorflow/issues/60654,yes,2.11.0,tf.math.abs,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs,,,,,2023-05-22T09:00:53Z,,
,https://github.com/tensorflow/tensorflow/issues/60549,yes,2.14.0,tf.signal.stft,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs,,,,,2023-05-09T20:14:39Z,,
,https://github.com/tensorflow/tensorflow/issues/60485,yes,2.14.0,tf.math.cumsum,Logical,InvalidArgumentError,"OpKernel was found, but attributes didn't match","InvalidArgumentError: Detected unsupported operations when trying to compile graph __inference_cumsum_7[_XlaMustCompile=true,config_proto=3175580994766145631,executor_type=11160318154034397263] on XLA_CPU_JIT: Cumsum (No registered 'Cumsum' OpKernel for XLA_CPU_JIT devices compatible with node {{node Cumsum}}
         (OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_INT8, Tidx=DT_INT32, exclusive=false, reverse=false){{node Cumsum}}",API Input Context,Supporting Specific Data Types,,,,,2023-05-03T16:51:04Z,,
,https://github.com/tensorflow/tensorflow/issues/60472,yes,2.14.0,tf.slice,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-05-02T16:34:56Z,,
,https://github.com/tensorflow/tensorflow/issues/59702,yes,2.13.0,tf.cast,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Negative Input Tensor,,,,,2023-02-15T20:59:06Z,,
FuzzGPT,https://github.com/tensorflow/tensorflow/issues/60418,no,2.11.0,tf.saved_model.save,Logical,Others,because it is not built,"WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.meta_architectures.ssd_meta_arch.SSDMetaArch object at 0x7f45581d7340>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.predictors.convolutional_keras_box_predictor.WeightSharedConvolutionalBoxPredictor object at 0x7f4558265760>, because it is not built.",API Input Context,Modeling Specific Inputs,,,,,2023-01-30T13:40:26Z,,
,https://github.com/tensorflow/tensorflow/issues/59215,yes,2.11.0,tf.debugging.enable_check_numerics,Logical,InvalidArgumentError,Graph execution error,InvalidArgumentError: Graph execution error:,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-01-10T14:12:55Z,,
,https://github.com/tensorflow/tensorflow/issues/57838,yes,2.11.0,tf.keras.layers.Conv2D,Logical,InvalidArgumentError,Trying to access resource,InvalidArgumentError: Trying to access resource Resource-2-at-0x234d2850 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0 [Op:__inference___call___77],Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2022-09-26T03:32:38Z,,
,https://github.com/tensorflow/tensorflow/issues/57748,yes,2.11.0,tf.keras.layers.Conv2D,Logical,Others,CUDNN_STATUS_NOT_SUPPORTED,tensorflow.python.framework.errors_impl.UnknownError: CUDNN_STATUS_NOT_SUPPORTED,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2022-09-19T11:24:41Z,,
,https://github.com/tensorflow/tensorflow/issues/57744,yes,2.11.0,tf.math.log,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2022-09-19T09:15:05Z,,
,https://github.com/tensorflow/tensorflow/issues/57664,yes,2.11.0,tf.keras.layers.Conv2D,Logical,ValueError,Exception encountered,"
    ValueError: Exception encountered when calling layer ""conv2d"" ""                 f""(type Conv2D).
    
    Negative dimension size caused by subtracting 2 from 1 for '{{node conv2d/Conv2D}} = Conv2D[T=DT_FLOAT, data_format=""NHWC"", dilations=[1, 1, 1, 1], explicit_paddings=[], padding=""VALID"", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true](x, conv2d/Conv2D/ReadVariableOp)' with input shapes: [2,1,2,2], [2,2,2,1].
    
    Call arguments received by layer ""conv2d"" ""                 f""(type Conv2D):
      • inputs=tf.Tensor(shape=(2, 1, 2, 2), dtype=float32)",Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2022-09-11T09:08:08Z,,
,https://github.com/tensorflow/tensorflow/commit/c5c0d33a365df5d8a81d920a9aeb0c390b67ee35,no,2.11.0,tf.image.convert_image_dtype,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Supporting Specific Data Types,,,,,2023,,
FuzzGPT,https://github.com/tensorflow/tensorflow/commit/bdf0934be81260b2e85aab9cba09bb77430f321c,yes,2.11.0,tf.custom_gradient,Logical,RuntimeError,is not supported when eager execution,Runtime Error:tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead.,API Input Context,Modeling Specific Inputs,,,,,2022,,
,https://github.com/tensorflow/tensorflow/commit/bd4d5583ff9c8df26d47a23e508208844297310e,yes,2.11.0,tf.ragged.constant,Vulnerability,Check failed,Aborted (core dumped),Others,API Input Context,Large Integer Argument,,,,,2022,,
,https://github.com/tensorflow/tensorflow/commit/73c5ff37f15e385eb3541089b183a3a66907842d,yes,2.11.0,tf.debugging.assert_type,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Supporting Specific Data Types,,,,,2020,,
